name: BuildAnimatorPlugin
version: 1.0
main: de.CypDasHuhn.BA.main.Main
api-version: '1.20'

commands:
  testcommand:
    description: testCommand
  buildsave:
    description: Save Structures
    aliases: bs
  buildload:
    description: Load Structures
    aliases: bl
