name: BuildPlugin
version: 1.0
main: de.CypDasHuhn.Build.main.Main
api-version: '1.20'

commands:
  testcommand:
    description: testCommand
  buildsave:
    description: Save Structures
    aliases: bs